/**
 * @file multiProcessingUtils.hh
 * @author Gjergji Luarasi (gjergji.luarasi@tum.de)
 * @brief
 * @version 0.1
 * @date 2023-04-12
 *
 * @copyright Copyright (c) 2023
 *
 */

#ifndef MULTIPROCESSINGUTILS_HH
#define MULTIPROCESSINGUTILS_HH

// Includes
#include <boost/interprocess/mapped_region.hpp>
#include <boost/interprocess/shared_memory_object.hpp>

// Default paramters
#define SHARED_MEMORY_SIZE 1024

// Setpoint value offsets
#define PANDA_TO_ENDOWRIST_MEMORY_OFFSET 0
#define MOTOR_0_TARGET_VELOCITY_OFFSET PANDA_TO_ENDOWRIST_MEMORY_OFFSET + 0
#define MOTOR_1_TARGET_VELOCITY_OFFSET PANDA_TO_ENDOWRIST_MEMORY_OFFSET + 8
#define MOTOR_2_TARGET_VELOCITY_OFFSET PANDA_TO_ENDOWRIST_MEMORY_OFFSET + 16
#define MOTOR_3_TARGET_VELOCITY_OFFSET PANDA_TO_ENDOWRIST_MEMORY_OFFSET + 24
// Measured value offsets
#define ENDOWRIST_TO_PANDA_MEMORY_OFFSET 512
#define MOTOR_0_ACTUAL_VELOCITY_OFFSET ENDOWRIST_TO_PANDA_MEMORY_OFFSET + 0
#define MOTOR_1_ACTUAL_VELOCITY_OFFSET ENDOWRIST_TO_PANDA_MEMORY_OFFSET + 8
#define MOTOR_2_ACTUAL_VELOCITY_OFFSET ENDOWRIST_TO_PANDA_MEMORY_OFFSET + 16
#define MOTOR_3_ACTUAL_VELOCITY_OFFSET ENDOWRIST_TO_PANDA_MEMORY_OFFSET + 24
#define MOTOR_0_ACTUAL_POSITION_OFFSET ENDOWRIST_TO_PANDA_MEMORY_OFFSET + 32
#define MOTOR_1_ACTUAL_POSITION_OFFSET ENDOWRIST_TO_PANDA_MEMORY_OFFSET + 40
#define MOTOR_2_ACTUAL_POSITION_OFFSET ENDOWRIST_TO_PANDA_MEMORY_OFFSET + 48
#define MOTOR_3_ACTUAL_POSITION_OFFSET ENDOWRIST_TO_PANDA_MEMORY_OFFSET + 56
#define MOTOR_0_ACTUAL_TORQUE_OFFSET ENDOWRIST_TO_PANDA_MEMORY_OFFSET + 64
#define MOTOR_1_ACTUAL_TORQUE_OFFSET ENDOWRIST_TO_PANDA_MEMORY_OFFSET + 72
#define MOTOR_2_ACTUAL_TORQUE_OFFSET ENDOWRIST_TO_PANDA_MEMORY_OFFSET + 80
#define MOTOR_3_ACTUAL_TORQUE_OFFSET ENDOWRIST_TO_PANDA_MEMORY_OFFSET + 88



// Namespaces
using namespace boost::interprocess;

// Functions

#endif