controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    cpp_relayer:
      type: cpp_relayer/CPPRelayer

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    franka_robot_state_broadcaster:
      type: franka_robot_state_broadcaster/FrankaRobotStateBroadcaster

franka_robot_state_broadcaster:
  ros__parameters:
    arm_id: panda

cpp_relayer:
  ros__parameters:
    arm_id: panda
